import pyautogui as pa
import time
pa.PAUSE = 0.5
pa.press('win')
pa.write('firefox')
pa.press('ENTER')
pa.PAUSE = 1
pa.write('uvv.br')
pa.press('ENTER')
pa.PAUSE = 3
pa.press('TAB')
pa.PAUSE = 0                      
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB') 
pa.press('TAB')
pa.press('TAB')
pa.press('ENTER')
pa.PAUSE = 3                        
pa.press('TAB')
pa.PAUSE = 0
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('ENTER')
pa.PAUSE = 1
pa.press('TAB')
pa.PAUSE = 0.5
pa.press('TAB')
pa.press('TAB')
pa.write('202203800')
pa.press('TAB')
pa.write('18022000')
pa.press('ENTER')
pa.PAUSE = 1
pa.press('TAB')
pa.PAUSE = 0
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('TAB')
pa.press('ENTER')